# List 리뷰

In [2]:
# 학생들의 점수 리스트로 저장(개별적으로 할 때는 평균등 계산하기가 불편해짐)
score = [100,80,95,75,80,92,94]
print(score)

[100, 80, 95, 75, 80, 92, 94]


In [3]:
# 항상 순서는 0번부터 시작
print(score[1])

80


In [4]:
len(score)

7

In [7]:
# 총 길이에서 -1을 하면 맨 끝값 출력
score[len(score)-1]

94

In [8]:
#뒤에서 부터 하고 싶을 경우 인덱스 -1부터 시작
score[-2]

92

In [6]:
score.append(60)

In [7]:
print(score)

[100, 80, 95, 75, 80, 92, 94, 60, 60]


In [11]:
min(score)

60

In [12]:
score.sort()

In [8]:
#max와 min을 사용하지 않고 sort를 사용하여 최소 쵀대 출력
score.sort()
print(score[0])
print(score[-1])

60
100


In [13]:
print(score)

[60, 75, 80, 80, 92, 94, 95, 100]


In [14]:
score[0]

60

In [11]:
import turtle as t

In [12]:
t.clear

for i in range(10,0,-1):
    if i%2 == 0:
        t.color('black')
    else:
        t.color('red')
    t.up()
    t.goto(0,-i * 10)
    t.down()
    t.begin_fill()
    t.circle(i*10)
    t.end_fill()
    
t.ht()
    

# numpy 시작

In [19]:
import numpy as np

In [20]:
test_array = np.arange(10)
test_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
test_array = np.array([1,4,5,8], float)
print(test_array) # 실수형이기 때문에 1. ~ 이런식으로 나옴
print(type(test_array[3])) # 인덱스 3의 데이터 타입 출력
print(test_array. dtype) # 리스트의 데이터 타입 확인 

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64


In [29]:
# array의 형태를 반환해 주는 함수
test_array.shape

(4,)

In [30]:
# array의 차원을 반환해주는 함수
test_array.ndim

1

In [27]:
#array의 총 elements 개수를 반환해주는 함수
test_array.size()

TypeError: 'int' object is not callable

In [35]:
te_ma = np.array([[1,2,3,4,],[1,2,3,4]])

In [36]:
te_ma

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [34]:
te_ma.shape

(2, 4)

In [37]:
re_ma = te_ma.reshape(8,)
print(re_ma)
print(re_ma.shape)

[1 2 3 4 1 2 3 4]
(8,)


In [39]:
reshape_mat = te_ma.reshape(-1,2 )
print(reshape_mat)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


## flatten
- 다차원의 array를 1차원으로 변환

In [41]:
reshape_mat.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4])

# indexing & Slicing

indexing : 인덱싱이란 "가리킨다"라는 의미

In [44]:
te_ma = np.array([[1,2,3,4],[5,6,7,8]])
te_ma

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
print(te_ma[0,0]) #이방식을 좀더 많이 사용 (row, columm)
print(te_ma[0][0])# 첫번쨰는 row, 두번쨰는, column

1
1


In [47]:
te_ma[1,3] = 800
print(te_ma)

[[  1   2   3   4]
 [  5   6   7 800]]


slicing : 잘라낸다는 의미

In [48]:
import numpy as np
te_ma = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [49]:
te_ma

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
te_ma[:,1:] # 앞뒤로 숫자를 생략한 경우 전체를 선택한다는 뜻(모든 행이 선택되고 1부터 끝까지 나타낸다는 뜻)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [58]:
te_ma[1:,:] #1행을 선택하고 전체열을 선택

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
te_ma[0:2] # list 등의 slicing 에서와 마찬가지로 슬라이싱의 뒷 숫자에는 원하는 숫자 +1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
te_ma[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
te_ma[1,3]

8

In [59]:
te_ma[0:2,2]

array([3, 7])

# arange 함수 
- 파이썬 기본 문법의 range 와 유사
- 범위를 지정하여 순차적인 값의 array를 생성
- np.arange(시작, 끝번호 +1 , 간격)
- reshape 함수와 함께 주로 사용

In [11]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [61]:
np.arange(0,11) #(시작, 끝+1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
np.arange(0,11,0.5) # range와 다르게 step으로 소수점도 가능

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [14]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

- sum : np.array의 elements의 합을 반환
- mean : np.array의 elements의 평균을 반환
- std : np.array의 elements의 표준편차를 반환

In [16]:
a = np.arange(0,10).reshape(-1,5)

In [17]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
a.sum()

45

In [19]:
a.mean()

4.5

In [20]:
a.std()

2.8722813232690143

# axis
- 여러 Operation Function들을 사용할 때, 기준이 되는 축 혹은 차원 

In [63]:
a = np.arange(1,13).reshape(3,4)

In [64]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a.sum(axis = 0) #2차원일 경우 axis = 0 이면 행방향 , axis = 1이면 열방향

array([15, 18, 21, 24])

In [67]:
a.sum(axis = 1)

array([10, 26, 42])

shape이 같은 array들 간의 기본적인 사칙연산 가능  # shape이 무조건 같아야함

In [27]:
a= np.array([1,2,3])

In [28]:
a + a

array([2, 4, 6])

In [29]:
a - a

array([0, 0, 0])

In [30]:
a*a

array([1, 4, 9])

In [31]:
a/a

array([1., 1., 1.])

### matrix multiplication
- 일반적인 매트릭스 간 곱셈은 dot 함수를 이용

In [69]:
mat_a = np.arange(1,5).reshape(2,2)
mat_a

array([[1, 2],
       [3, 4]])

In [70]:
mat_a.dot(mat_a)

array([[ 7, 10],
       [15, 22]])

all & any
all : array의 모든 elements 가 조건에 만족할 때만 True를 반환
any : array의 한 elements 만이라도 조건에 만족하면 True를 반환

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.any(a>5), np.any(a<0)

(True, False)

In [35]:
np.all(a>5), np.all(a>=0)

(False, True)

In [36]:
a = np.array([1,3,0])
b = np.array([5,2,1])


In [37]:
a>b

array([False,  True, False])

In [39]:
(a>b).any()

True

where : 조건에 따라서 값을 할당해주거나, 조건에 맞는 index값을 반환시키고 싶을 경우 사용

In [41]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.where(a<5,0,1)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [72]:
b= np.array([1,2,np.nan])

In [73]:
b

array([ 1.,  2., nan])

In [76]:
np.isnan(b)

array([False, False,  True])

#### argmax& argmin
- array안의 최대값과 최소값의 인덱스를 알려줌
- axis를 기반으로 적용이 가능하다(다차원일 경우)

In [78]:
c = np.array([1,5,3,9,8])
print(np.argmax(c))
print(np.argmin(c))

3
0


In [79]:
d = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
d

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [80]:
np.argmax(d, axis = 1)

array([3, 1, 1], dtype=int64)

In [81]:
np.argmin(d, axis = 0)

array([0, 0, 2, 2], dtype=int64)

## boolean index
- 특정조건에 따른 True or False 값을 index로 이용해서 True에 해당하는 값들 만을 추출

In [82]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [83]:
test_array[test_array>3]

array([4., 8., 9., 7.])