In [47]:
import turtle as t

In [53]:
color = ['red','black','blue','green','pink','yellow','white','brown','purple','gray']

In [66]:
for i in range(10,0,-1):
    t.color(color[i-1])
    t.up()
    t.goto(0,-i*10)
    t.down()
    t.begin_fill()
    t.circle(i*10)
    t.end_fill()
t.up()    
t.ht()
t.color('black')
t.goto(200,0)
t.write('60171100 윤민혁',False,'center',('',15))

In [65]:
t.clear()

In [56]:
import numpy as np

In [57]:
a = np.arange(0,10)

In [59]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
print(np.where(a>5,0,a))

[0 1 2 3 4 5 0 0 0 0]


In [62]:
print('60171100 윤민혁')

60171100 윤민혁


In [67]:
import turtle as t
for i in range(0,6,1):
for k in range(0,7,1):
    t.dot(10)

IndentationError: expected an indented block (<ipython-input-67-068c084d5189>, line 3)

In [68]:
import numpy as np

In [69]:
a= np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [105]:
b = np.where((a>4) & (a<14) ,(a*-1) ,a)

In [106]:
b

array([  1,   3,  -5,  -7,  -9, -11, -13,  15,  17,  19])

In [109]:
b[::-1]

array([ 19,  17,  15, -13, -11,  -9,  -7,  -5,   3,   1])

In [112]:
x = np.array([1,1,1,1,1,1,1,1,1,1,1,1]).reshape(3,4)

In [113]:
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [117]:
y = x.reshape(2,6)
print(y)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [118]:
np.transpose(y)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [119]:
y.sum()

12

In [120]:
import turtle as t

IndentationError: expected an indented block (<ipython-input-121-ced4b2f923ab>, line 6)

In [122]:
import turtle as t

IndentationError: expected an indented block (<ipython-input-122-ced4b2f923ab>, line 6)

In [124]:
import turtle as t
window = t.Screen()
worker = t.Turtle()
worker.speed(0)
for x in range(-200, 200, 50):
for y in range(-200, 200, 50):
    worker.penup()
    worker.setposition(x, y)
    worker.pendown()
    worker.circle(20)
    window.exitonclick()

IndentationError: expected an indented block (<ipython-input-124-729ec33be616>, line 6)

In [132]:
n = int(input("Enter a number of n: "))
for i in range(n):    
    print(" "*(n-i-1),end="")    
    for j in range(i+1):        
        print("* ",end="")    
    print()


Enter a number of n: 5
    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [136]:
import turtle as t

t.up()
for i in range(0,7):
    for x in range(0,6-i):
        print(" ", end="")
    for y in range(0,i+1):
        print("* ",end="")
    print('\r')

      * 
     * * 
    * * * 
   * * * * 
  * * * * * 
 * * * * * * 
* * * * * * * 


In [137]:
import turtle
turtle.position()
(150.00,-0.00)
turtle.color("blue")
astamp = turtle.stamp()
turtle.fd(50)
turtle.position()
(200.00,-0.00)
turtle.clearstamp(astamp)
turtle.position()
(200.00,-0.00)

(200.0, -0.0)

In [3]:
import turtle as t
t.up()
x=0
y=0
for i in range(0,7,1):
    for y in range(0,i,1):
        t.dot(30,'white')
    for x in range(7-i):
        t. goto(x*30, y*30)
        t.dot(30,'black')
    x = 0

