# 4주차 NumPy 요약

# 배열 만들기

60171100 윤민혁

In [1]:
import numpy as np

In [2]:
#두 리스트([1,2,3],[5,6,7])로 각각 배열을 만들어보자
a1 = np.array([1,2,3])
a2 = np.array([5,6,7])
print(a1)
print(a2)

[1 2 3]
[5 6 7]


In [4]:
#두 배열을 더해보자
print(a1+a2) #방법 1
print(np.add(a1,a2)) # 방법 2

[ 6  8 10]
[ 6  8 10]


In [5]:
#배열의 모든 원소에 5를 더해보자
a1+5

array([6, 7, 8])

In [12]:
#0으로 채운 3행 3열의 배열을 만들어보자
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#위의 배열을 정수형으로 생성해보자
np.zeros([3,3],dtype = 'int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

60171100 윤민혁

In [18]:
#1로 채운 3행 3열의 배열을 만들어보자
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#특정값으로 채운 3행 3열의 배열을 만들어보자
np.full([3,3],3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [7]:
#난수로 배열 생성하기
np.random.random([4,4])

array([[0.14546872, 0.03375446, 0.18590538, 0.00269615],
       [0.69706611, 0.58698815, 0.70285164, 0.45012414],
       [0.82927931, 0.21774993, 0.28251895, 0.88478166],
       [0.71727111, 0.41303746, 0.51567696, 0.09288448]])

In [8]:
#난수의 평균과 표준편차를 지정하여 배열만들기
np.random.normal (0,1,(3,3))

array([[ 1.33319204, -0.24812445, -0.70486164],
       [-1.05512863, -1.14291762, -2.42846495],
       [-0.98859454,  1.53108827, -2.03064538]])

In [9]:
#임의구간의 난수로 배열만들기
np.random.randint(0,10,[3,3])

array([[5, 9, 6],
       [7, 3, 0],
       [7, 6, 7]])

In [30]:
#단위행렬 만들기
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

60171100 윤민혁

In [2]:
import 
x = np.random.randint(10,size=(3,4,5),dtype='int')

#차원 개수
print('차원의 크기:',x.ndim)
#차원별 크기
for i in range(3):
    print(i+1,'차원의 크기:',x[i].size)
#전체 배열 크기
print('전체 배열 크기:',x.shape)
#데이터 타입
print('x의 데이터 타입: ', x.dtype)

차원의 크기: 3
1 차원의 크기: 20
2 차원의 크기: 20
3 차원의 크기: 20
전체 배열 크기: (3, 4, 5)
x의 데이터 타입:  int32


In [28]:
x=np.arange(10)

#홀수만 출력
print(x[x%2 ==1])
#3부터 5사이만 출력
print(x[3:6])

[1 3 5 7 9]
[3 4 5]


# 배열 사본 생성하기

60171100 윤민혁

In [29]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
x_sub = x
x_sub[0] = 10
print(x_sub)

[10  1  2  3  4  5  6  7  8  9]


In [31]:
x

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [32]:
x_copy = x.copy()
x_copy[0] = 5
print(x_copy)

[5 1 2 3 4 5 6 7 8 9]


In [34]:
x

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

# 배열 연결
60171100 윤민혁

In [36]:
#같은 차원의 배열 연결
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3,2,1],[6,5,4]])

In [38]:
np.concatenate([x,y], axis = 0) # 수직 스택

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [39]:
np.concatenate([x,y], axis = 1) # 수평 스택

array([[1, 2, 3, 3, 2, 1],
       [4, 5, 6, 6, 5, 4]])

In [40]:
#혼합된 차원의 배열 연결
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3,2,1],[6,5,4], [3,2,1]])
z = np.array([[7],[10]])

In [42]:
np.vstack([x,y]) # ㅌ와 y의 수직 스택

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4],
       [3, 2, 1]])

In [44]:
np.hstack([x,z]) # x와 z의 수평 스택

array([[ 1,  2,  3,  7],
       [ 4,  5,  6, 10]])

# 비교, 마스크, 부울 로직
60171100 윤민혁

In [47]:
# 비교 연산자
x = np.array([1,2,3,4,5])

In [48]:
x<2

array([ True, False, False, False, False])

In [49]:
x != 2

array([ True, False,  True,  True,  True])

In [50]:
x ==2

array([False,  True, False, False, False])

In [52]:
x = np.random.randint(1,10, (3,4))
x

array([[5, 3, 2, 5],
       [9, 7, 9, 6],
       [2, 6, 7, 7]])

In [53]:
x<5

array([[False,  True,  True, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [54]:
#요소 개수 세기
np.sum(x<5)

3

In [60]:
#각 열에서 5보다 작은 요소 개수 세기
print(np.sum(x<5, axis = 1))
#각 행에서 5보다 작은 요소 개수 세기
print(np.sum(x<5, axis = 0))

[2 0 1]
[1 1 1 0]


In [63]:
#두 조건 식에서 요소 개수 세기
np.sum((x>=4)&(x<=6))

4

In [65]:
#any, all 함수
np.any(x<5) # 5보다 작은 요소가 1개라도 있는가?

True

In [66]:
np.all(x<5) # 모든 요소가 5보다 작은가?

False

# 정렬
60171100 윤민혁

In [67]:
x = np.array([2,10,3,8,5])
np.sort(x)

array([ 2,  3,  5,  8, 10])

In [68]:
z = np.random.randint(0,10, (4,6))
z

array([[9, 6, 5, 2, 5, 4],
       [4, 8, 8, 4, 8, 2],
       [2, 9, 8, 6, 9, 8],
       [5, 2, 3, 4, 8, 5]])

60171100 윤민혁

In [69]:
np.sort(z, axis = 0) # 행정렬

array([[2, 2, 3, 2, 5, 2],
       [4, 6, 5, 4, 8, 4],
       [5, 8, 8, 4, 8, 5],
       [9, 9, 8, 6, 9, 8]])

In [70]:
np.sort(z, axis = 1) # 열정렬

array([[2, 4, 5, 5, 6, 9],
       [2, 4, 4, 8, 8, 8],
       [2, 6, 8, 8, 9, 9],
       [2, 3, 4, 5, 5, 8]])

In [79]:
#내림차순 행 정렬
-np.sort(-z, axis = 0)

array([[9, 9, 8, 6, 9, 8],
       [5, 8, 8, 4, 8, 5],
       [4, 6, 5, 4, 8, 4],
       [2, 2, 3, 2, 5, 2]])